### ISSUE TITLE
Documenting Message.Date timezone

### ISSUE THREAD

**Issue by sztanpet** [go-telegram-bot-api/telegram-bot-api#240]
Hi, can't seem to find any information about what timezone the Message.Date is in, I can see that it's from a unix timestamp, but that doesn't have any timezone information. The only sane thing to do on Telegrams side is to send it as UTC, but maybe it's not sane?

Either way, it should be documented whether Date has any specific timezone, or it depends on the sending users.

**Comment by njittam** [comment]
The api itself is documented at https://core.telegram.org/bots/api#message.
It says about the date field: `Date the message was sent in Unix time` so it is a unix time stamp.

I think the Unix Time stamp is a great way to keep track of time because it does not care about timezones or daylight saving. It is just the number of seconds since 1-1-1970 UTC. So there should be no need to know the timezone. https://www.unixtimestamp.com says:

 ```

The unix time stamp is a way to track time as a running total of seconds.
 This count starts at the Unix Epoch on January 1st, 1970 at UTC. 
Therefore, the unix time stamp is merely the number of seconds between a particular date and the Unix Epoch. 
It should also be pointed out (thanks to the comments from visitors to this site) that this point in time technically does not change no matter where you are located on the globe. 
This is very useful to computer systems for tracking and sorting dated information in dynamic and distributed applications both online and client side.
```

**Comment by sztanpet** [comment]
Had to deal with way too many apis giving unix timestamps not based on UTC to rather see the documentation spelling it out clearly
