### ISSUE TITLE
Edited message cause failure bot

### ISSUE THREAD

**Issue by ThanhPP** [go-telegram-bot-api/telegram-bot-api#330]
If a command message is eddited. The bot will fatal and show 
`
goroutine 1 [running]:
github.com/go-telegram-bot-api/telegram-bot-api.(*Message).IsCommand(...)
        D:/go/pkg/mod/github.com/go-telegram-bot-api/telegram-bot-api@v4.6.4+incompatible/types.go:181
`
Unless i delete the message or call a new command, the bot will automatically fatal when i restart it

**Comment by Syfaro** [comment]
Can you provide a code example that triggers this? 

`IsCommand` shouldn't be getting called by itself, although it's concerning that it panics.

**Comment by ThanhPP** [comment]
https://github.com/DeltaTeamApp/Telegram_Chatbot/blob/6432923df114e8e79505d4e96ffe13e48c2122f6/main.go#L33
Here is my code. When the app is running and you modified one command that is already been done. It will cause panic

**Comment by Syfaro** [comment]
Your issue is that `update.Message` is nil when you receive an edited message update.

Each update is a struct with many fields. Only one of those fields will be set to a non-nil value. You might want to check if `update.Message != nil` then handle the update as a regular message, check if `update.EditedMessage != nil` to handle edits, etc. Then when working with an edited message, you'd need to do `update.EditedMessage.IsCommand()` and for every other field you want to access. 

If you only want to process messages, you could update your code as follows: 

```go
for update := range updates {
	if update.Message == nil { // If the Message is nil, skip this update
		continue
	}

	// Your message handling 
}
```
