### ISSUE TITLE
expect / accept response

### ISSUE THREAD

**Issue by sifaaa** [go-telegram-bot-api/telegram-bot-api#337]
Tell me how to get the bot to take a specific answer?
The bot constantly watch updates and the answer may not be the next update.
For example, a bot asks what is your name? and you have to give an answer.
And in parallel, someone else performs other actions with him.

Because of this, it is unclear how to ask a question through a button and that the answer relates specifically to this button, and not to the global update of new messages

I use google translator

**Comment by Oppen** [comment]
The API just works with an update queue, it's the bot's responsibility to see what matters to it.
You can save some bandwidth signaling which _types_ of events you care about, but even that way you may get uninteresting messages, because it doesn't discard what's already in the queue.
Your code will need to take care of that.

Said that, this package doesn't support that feature. I have just submitted a PR for that #344.
