### ISSUE TITLE
Document type fields

### ISSUE THREAD

**Issue by tjhorner** [go-telegram-bot-api/telegram-bot-api#380]
The [fields in the API types](https://github.com/go-telegram-bot-api/telegram-bot-api/blob/master/types.go) don't have very much documentation; it would be ideal for them to inherit their documentation from the [official Telegram API docs](https://core.telegram.org/bots/api), perhaps with anything specific to the library as well.

For example, the `Message` type was documented in #379.

**Comment by ilyakaznacheev** [comment]
I'll do that.

If you don't mind, I will split the task into a couple of PRs.

**Comment by ilyakaznacheev** [comment]
Done. Added documentation for the types I was able to find in the API.

**Comment by tjhorner** [comment]
@ilyakaznacheev Awesome, thanks! I will take a look at the PRs sometime next week.

**Comment by ilyakaznacheev** [comment]
@tjhorner thanks! There is nothing but comments (Godoc), so it probably shouldn't take a huge amount of time.

I've changed some descriptions a bit to make them look more like idiomatic Godoc, rather than just a copy-paste from API docs. But the copying, pasting, and formatting itself took a lot more time, then I expected :)

**Comment by tjhorner** [comment]
Great work @ilyakaznacheev, thanks again :)
