### ISSUE TITLE
How to send a broadcast message to every user

### ISSUE THREAD

**Issue by alambertt** [go-telegram-bot-api/telegram-bot-api#459]
I want to send a broadcast message (like a promo message) to every user that has started a conversation with my bot. How can I do that? Thks

**Comment by temamagic** [comment]
Bot API doesn't have method to send message for all users. You must have user ID's in database and send them one-by-one

**Comment by tjhorner** [comment]
Telegram has [tips on how to do this](https://core.telegram.org/bots/faq#broadcasting-to-users).

Since this is not related to the library itself, I am going to close this. If you need help implementing the methods Telegram suggests, feel free to open a thread in the [discussions](https://github.com/go-telegram-bot-api/telegram-bot-api/discussions) or ask in [the development group](https://telegram.me/go_telegram_bot_api), as @temamagic mentioned.
