### ISSUE TITLE
Send photo by url

### ISSUE THREAD

**Issue by Hamper** [go-telegram-bot-api/telegram-bot-api#67]
If I use
```go
file := "http://...../img.jpg"
msg := tgbotapi.NewPhotoUpload(update.Message.Chat.ID, file)
bot.Send(msg)
```
I got "Bad Request: there is no photo in the request"

If I use
```go
file := "http://...../img.jpg"
msg := tgbotapi.NewPhotoUpload(update.Message.Chat.ID, nil)
msg.FileID = file
bot.Send(msg)
```
I got "open ...: no such file or directory"

but if I use
```go
file := "http://...../img.jpg"
msg := tgbotapi.NewPhotoUpload(update.Message.Chat.ID, nil)
msg.FileID = file
msg.UseExisting = true
bot.Send(msg)
```
all works

It may be possible to make to support this method in NewPhotoUpload if last argument is url?

**Comment by Syfaro** [comment]
It works only if it actually is a `url.URL`. `NewPhotoUpload` accepts an `interface{}` for `file`, because it changes the action based on its type. 

[Relevant docs](https://godoc.org/github.com/go-telegram-bot-api/telegram-bot-api#BotAPI.UploadFile) and [relevant code](https://github.com/go-telegram-bot-api/telegram-bot-api/blob/master/bot.go#L154).

**Comment by Syfaro** [comment]
Closing this as nothing appears to be wrong and there has been no response.
