### ISSUE TITLE
Improvement: Option to stop the update loop of the bot

### ISSUE THREAD

**Issue by sandler31** [go-telegram-bot-api/telegram-bot-api#84]
This is a proposal for a feature which will allow a user to stop the update loop (the goroutine) that is created on a call to ```GetUpdatesChan```.

### Rationale
The rationale behind this request is to allow safe cleaning of a bot listener created with the polling method, without killing the whole program.

### Use case
An example for such a need would be in an application which starts multiple listeners for different bots, and from time to time needs to stop some of them, and listen to new ones, according to a configuration. 
What would happen currently is there is currently no way to stop a bot update loop - a user can use goroutines, and exit them according to some signal in his application, but the update loop will still run internally, and if in the future the user will try to create a listener to the same bot, he will get conflicts on calls to the Telegram API.

### Solution
I've written code that allows to do that, and will submit a PR, hope it'll get accepted as I think this is a useful feature, anyways, if it's not implemented good enough we can discuss how it should be implemented here :)

**Comment by Syfaro** [comment]
This issue came up before, https://github.com/go-telegram-bot-api/telegram-bot-api/issues/52

As I told them, the whole function is only a few lines of code so I'd suggest just implementing such a function yourself with your custom method for stopping. Given that the provided updates function is somewhat opinionated (how it logs errors and hardcoded time delay), it's not unreasonable to expect others to rewrite it anyway. I'd especially not like to break compatibility with older versions for a feature few people are likely to use.

**Comment by sandler31** [comment]
Oh, I see, didn't find that issue before.
The problem is, at least from what I understand, that it's not really possible to create an external method that will stop the update loop, as it starts a goroutine with an infinite loop without a break statement anywhere.
The only way would be to recreate the ```GetUpdatesChan``` method outside the package, but that is somewhat weird, imho.
Why are you against having a stop method inside the package?
